Update building-contributing.md
I was caught in an install circle:

```
$ brew unlink ddev && brew install drud/ddev/ddev --HEAD --fetch-HEAD
...
Error: The following flag:
  --HEAD
requires building tools, but none are installed.
Install Clang or run `brew install gcc`. 

$ brew install clang                                                 
Warning: No available formula with the name "clang"

$ brew install gcc
Running `brew update --auto-update`...
Warning: gcc 11.3.0_2 is already installed and up-to-date.
To reinstall 11.3.0_2, run:
  brew reinstall gcc
```

Running the following resolved the issue: `sudo apt install build-essential gcc`